### ISSUE TITLE
Size cache memory leak

### ISSUE THREAD

**Issue by Lisimbas** [iLexiconn/LLibraryLegacy#60]
In the 1.7.10 branch, in the ServerEventHandler, the size cache keeps a reference to every entity it ever sees since it uses them as keys. This prevents them from being garbage collected. I have a heap dump here where the size cache is keeping a bit over 2 GB of entities alive (roughly 200k of them), and that was after just a few hours of running. Perhaps a WeakHashMap is better here?

**Comment by iLexiconn** [comment]
I'll take a look at it, thanks :)

**Comment by ljfa-ag** [comment]
The same for [this HashMap](https://github.com/iLexiconn/LLibrary/blob/1.7.10/src/main/java/net/ilexiconn/llibrary/common/entity/EntityHelper.java#L37). Using a WeakHashMap will make sure that the keys of the map will still be garbage collected when they are not otherwise being referenced. Please keep that in mind wherever you use collections.
